argo-cd:
  configs:
    params:
      server.insecure: true
  server:
    service:
      type: ClusterIP
    replicas: 1
  repoServer:
    replicas: 1
  applicationSet:
    replicas: 1
  controller:
    replicas: 1
  redis:
    enabled: true
  dex:
    enabled: false
    