apiVersion: v2
name: headlamp
type: application
version: 0.1.0
appVersion: "0.40.0"

dependencies:
  - name: headlamp
    version: "0.40.0"
    repository: "https://kubernetes-sigs.github.io/headlamp/"