apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: headlamp-vs
  namespace: headlamp
spec:
  hosts:
  - headlamp.local
  gateways:
  - istio-system/gateway
  http:
  - route:
    - destination:
        host: headlamp.headlamp.svc.cluster.local
        port:
          number: 80
