services:
  cloud-provider-kind:
    image: registry.k8s.io/cloud-provider-kind/cloud-controller-manager:v0.10.0
    container_name: cloud-provider-kind
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock