{{- if .Values.istio.enabled -}}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ include "headlamp.name" . }}-vs
  namespace: {{ .Values.istio.namespace | default "headlamp" }}
spec:
  hosts:
  - {{ .Values.istio.host | default "headlamp.local" }}
  gateways:
  - {{ .Values.istio.gateway | default "istio-system/gateway" }}
  http:
  - route:
    - destination:
        host: {{ include "headlamp.name" . }}.{{ .Values.istio.namespace | default "headlamp" }}.svc.cluster.local
        port:
          number: 80
{{- end -}}
