gha-runner-scale-set:
  githubConfigUrl: "https://github.com/noh4nsen/lab"
  githubConfigSecret: arc-github-secret
  controllerServiceAccount:
    namespace: arc-systems
    name: arc-controller-gha-rs-controller
  containerMode:
    type: "dind"